export const AVAILABLE_MODELS = {
  classification: {
    alexnet: { label: "AlexNet" },
    resnet18: { label: "ResNet18" },
    resnet34: { label: "ResNet34" },
    resnet50: { label: "ResNet50" },
    resnet101: { label: "ResNet101" },
    resnet152: { label: "ResNet152" },
    resnext50_32x4d: { label: "ResNeXt50" },
    resnext101_32x8d: { label: "ResNeXt101" },
    wide_resnet50_2: { label: "WideResNet50" },
    wide_resnet101_2: { label: "WideResNet101" },
    vgg11: { label: "VGG11" },
    vgg13: { label: "VGG13" },
    vgg16: { label: "VGG16" },
    vgg19: { label: "VGG19" },
    squeezenet1_0: { label: "SqueezeNet" },
    inception_v3: { label: "InceptionV3" },
    densenet121: { label: "DenseNet121" },
    densenet161: { label: "DenseNet161" },
    densenet169: { label: "DenseNet169" },
    densenet201: { label: "DenseNet201" },
    googlenet: { label: "GoogLeNet" },
    mobilenet_v2: { label: "MobileNetV2" },
    mnasnet1_0: { label: "MNASNet" },
    shufflenet_v2_x1_0: { label: "ShuffleNetV2" },
  },
  detection: {
    fasterrcnn_resnet50_fpn: { label: "Faster RCNN ResNet50 FPN" },
    fasterrcnn_resnet50_fpn_v2: { label: "Faster RCNN ResNet50 FPN v2" },
    fasterrcnn_mobilenet_v3_large_fpn: {
      label: "Faster RCNN MobileNetV3-Large FPN",
    },
    ssd300_vgg16: { label: "SSD300 VGG16" },
    ssdlite320_mobilenet_v3_large: { label: "SSDLite320 MobileNetV3-Large" },
    fcos_resnet50_fpn: { label: "FCOS ResNet50 FPN" },
    retinanet_resnet50_fpn: { label: "RetinaNet ResNet50 FPN" },
    retinanet_resnet50_fpn_v2: { label: "RetinaNet ResNet50 FPN v2" },
  },
};
